language: node_js
node_js: node
services:
- mongodb
env:
  global:
    secure: Tk8nSRl5f8q/MJHFoIUqtVPViVOU3BW2O5H3m3+VffaH1xtO6jPOPqzUwUMXHceLk5Rj1CRKhzKy1rJ4qsdYvrLL3UMRBohyyBAtLtFZ9OOtqd7nGP8lhkxDJMhY1ZoDTQhFgTCAOJyQFpC5o7Woix5Ldg+3eTy0t5ZUnsF/Y1HF56Xumwp6m16DwLYkRlFnK1IBxy38inYomDGASc20e3BlFMzm+6rw9cyzZpCYmRYR9kYVyDNoUggfCKKrh+hfsOaG+hxx0RcXfGnwVaHtRiayV+EVWDfjaZ7efrYteD4eCZ6BYfQXYuU9JZMJKKEdSmdrLcVWGIw5VIgnuIpPX19sLTVqOhOp4XJc1Iceii/Ba2MZhmllyesvoS4e/NZj++W/l4eq5SpDw98255r625hg/4havk2SXsvoL1xL6lfkgZ3P36mswbVKqfviZ4H6M03n6O5QdyVeh724S6i6hGaQcGRDuWaM7Kw16+tRlT4OW9WYQjfWlMFJWn/xrqVe9LK6kFVn0HCItFVHSa+H71zRhNl5n5TpS0E9v4rWomkbzzZ5APuU4Qn2meLgwsdtvuGs8jTjGeCFN/v30OqcGyzNJV8niuBxK/FNBZ+YTnxOYPpSFIn6p0lFYRPz1e3U0z5uUwggPlgfKb/nDWd0ECNJkhdMerzLsyaCwvxcKNs=
